### ISSUE TITLE
Specify location for cycling files

### ISSUE THREAD

**Issue by steoxley** [metomi/rose#1333]
It would be useful if we could separate out the share directory into two areas.
 1. An area for files which are shared only between cycles, which are regularly house-kept.
 2. An area for files which are shared throughout the whole suite.

This would allow different storage areas to be used. e.g. 1, could be directed to a storage area which is deleted more aggressively than 2.

**Comment by hjoliver** [comment]
I just sent an email to @matthewrmshin about this, and then saw this issue.  I wrote essentially the following (edited here after re-reading it):

I guess I don't see a clear need to assume or impose a particular suite share structure because the potential uses of share are quite varied, e.g.: big files used throughout the suite run, cycle-point directories that are house-kept at some offset from current cycle point, and flat directories of cycle-point labelled files (perhaps house-kept as a rolling archive) e.g. for accumulating verification stats. Each of these categories of files would require different housekeeping, and additionally there might be physical storage requirements (due to file size or number) that differ between (and potentially within) these groups ... hence, there is potentially a need for more than two top-level share directories.  So ... I think the most sensible thing to do is have a single top-level official suite share directory (i.e. ```~/cylc-run/<SUITE>/share/```) and arbitrary user-determined sub-directories.  You can already do this with a raw cylc suite, of course.  The problem for rose suites (correct me if I'm wrong) is just that ```rose prune``` assumes everything is under ```share/data/<cycle-point>/``` (and now you are proposing two locations instead of one).  It seems to me the only thing we need to do to facilitate any conceivable use of the share space is to make ```rose prune``` target locations configurable (it could still default to current behaviour).
