### ISSUE TITLE
rose edit: nicer add section interface

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#1655]
Users should be able to add sections with all the compulsory options added with sensible defaults (if possible).

**Comment by matthewrmshin** [comment]
I thought the main reason for options to be compulsory is because they have no sensible defaults. If they have sensible defaults then the defaults should be added to the code, not the metadata, and the settings should be optional instead of compulsory.

**Comment by benfitzpatrick** [comment]
I just meant the usual guess-a-sensible value mechanism - https://github.com/metomi/rose/blob/702d5a47/lib/python/rose/variable.py#L241

**Comment by matthewrmshin** [comment]
> I just meant the usual guess-a-sensible value mechanism

Even this can be problematic, because:
* You should really use the missing data indicator instead of 0 for integers and real numbers, but then surely that's the default in the actual application any way?
* If *false* and the empty string can be used as sensible values, they should probably be the default in the actual application?
