### ISSUE TITLE
rose suite-run check for suite already running

### ISSUE THREAD

**Issue by hjoliver** [metomi/rose#1829]
Bug report from NIWA operations:

> Hi Hilary,
There’s a minor issue with rose; when starting or restarting a suite at the same time a different
 suite is running a polling task that polls the suite you are trying to start, you get rose fail messages
 declaring that the suite may already be running:
```
[ecox_test@fc-3 niwa1-aa101]$ cd ../niwa1-aa110; rose suite-run --restart
[FAIL] Suite "niwa1-aa110" may still be running.
[FAIL] Host "localhost" has process:
[FAIL]     37213 python /oper/admin/um_fcm/cylc/cylc-6.8.1/bin/cylc-suite-state
      --task=ingest_site --point=20160214T18 --status=succeed --interval=60 
      --max-polls=240 --run-dir=/home/ecox_test/cylc-run niwa1-aa110
[FAIL] Try "rose suite-shutdown --name=niwa1-aa110" first?
```
 Is this a known issue?

**Comment by matthewrmshin** [comment]
This is not a known issue.

The pattern for `pgrep` can be found here:
https://github.com/metomi/rose/blob/master/lib/python/rose/suite_engine_procs/cylc.py#L119

It is an attempt to match `cylc run` and `cylc restart` commands. It is unfortunate that it matches the `cylc suite-state` command, probably due to the `--run-dir=/home/ecox_test/cylc-run` bit.
