### ISSUE TITLE
Ability to setup striping when root-dir created

### ISSUE THREAD

**Issue by ColemanTom** [metomi/rose#2154]
I have been discussing this with Joan Fernon and given we typically have our share and work root-dirs on a lustre disk, could we have some way to define striping when those directories are created. It feels more logical and robust to have it done at creation time rather than in a separate task.

e.g.
```
root-dir{work}=lustredisk=/a/b/c,stripesize=X,stripecount=X,etc...
```

**Comment by matthewrmshin** [comment]
Hi @ColemanTom I have had a quick chat with one of our local HPC experts. In general, it looks like that this is unnecessary as well as undesirable - because specific striping should only be configured for special files for applications that demand a lot of parallel I/O, and should not be configured to all general files in a suite.

I am closing this as a *won't fix* for now. Please feel free to re-open if you really think there is a requirement.
