### ISSUE TITLE
Unable to stop rose/cylc suite

### ISSUE THREAD

**Issue by puneet336** [metomi/rose#2155]
Hi all,
I am trying to stop a suite on my machine as - 

[machine1][/home/user1/source]> rose suite-run --name=test2
[FAIL] Suite "test2" has running processes on: machine1
[FAIL] Try "cylc stop 'test2'" first?
[machine1][/home/user1/source]> cylc stop 'test2'
Cannot connect: https://machine1:43021/command/set_stop_cleanly?kill_active_tasks=False: HTTPSConnectionPool(host='machine1', port=43021): Max retries exceeded with url: /command/set_stop_cleanly?kill_active_tasks=False (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa875a9b390>: Failed to establish a new connection: [Errno 111] Connection refused',))
[machine1][/home/user1/source]> rose suite-run --name=test2
[FAIL] Suite "test2" has running processes on: machine1
[FAIL] Try "cylc stop 'test2'" first?
[machine1][/home/user1/source]>

For rerunning  rose suite , currently i have to - 
`[machine1][/home/user1/source]> rm -rf ~/cylc-run/test2/`
With aforementioned approach , i have to restart my suite from the beginning.
This approach poses an issue if i want to resume my suite from a lengthy "completed" task.

I am happy to delete a cylc specific single file - for which i don;t end up "restarting" my suite from scratch.  Please let me know if further information is required from my end.

**Comment by matthewrmshin** [comment]
Hi @puneet336 Have a look at `~/cylc-run/test2/.service/contact`. Note down the process `PID` in the value of `CYLC_SUITE_PROCESS`. Do a `ps -f PID` (replace `PID` with the actual process ID). Is the process still running? If it is still running, we need to establish why the server program is refusing connection. Otherwise, we need to figure out why the server has left behind the contact file.

This appears to be an issue to do with usage or site setting. Close as invalid for now.

For usage issues, please email us. Our email address can be found [here](https://github.com/metomi).
