### ISSUE TITLE
rosie go: clarify meaning of copy suite

### ISSUE THREAD

**Issue by dpmatthews** [metomi/rose#2397]
Apparently some users get confused between the `Checkout Suite` (i.e. create a local working copy) and the `Copy Suite` options. We could make this clearer by changing the menu option to `Copy to New Suite`.

**Comment by soi521** [comment]
Hi Metomi,

Thanks very much to Dave M for raising this issue officially in response to my email of 27th Feb. Since the problem is the word "Copy", however, could it be changed instead to "Create and checkout new suite"?

A bit of context that might be helpful:

I run training tutorials for using the JULES model through Rose/Cylc and the FCM version control system. The "Copy suite" option in Rosie Go is one that I have to explain repeatedly every time I train anyone. For newbies this is very odd terminology because it doesn't correspond to the "Create branch and checkout" terminology used by FCM for code branches.

Just to be clear: this is NOT a complaint that the "copy suite" function doesn't work - it works perfectly! - it's just I personally find I have to explain what it does many, many times to students and a little rename would make my life very, very much easier.

The "Checkout suite" option on the same menu is just perfect because the term "checkout" is also used for code branches (command "fcm co") and students can easily see the connection between the two. However, "Copy suite" doesn't correspond to any FCM command "fcm copy": it corresponds most closely to fcm bc followed by fcm co so a more logical option in this menu I feel would be "Create and checkout new suite" (I understand that each rose suite is its own svn project unlike code branches, but this point still stands).

Dave M did point out that the "Copy suite" option in this menu does correspond to the rosie copy command, but note that (i) rosie copy is only an alias for rosie create and (ii) as students unfailingly tell me once they do understand what these options do in Rosie, the "checkout" option is actually closer to what the English word "copy" means because it's function is to give you a local copy of that suite.

Many thanks if this could be updated sometime (probably after Cylc 8).

Best regards,
Toby

**Comment by wxtim** [comment]
At Rose 2:
- CLI: Summary from `rosie copy --help` is `rosie copy  : Create a new suite and copy content from an existing one.`
- Check the Rosie tutorial. I've added a line: #2517 
- No Rose 2 Rosie GUI.
