### ISSUE TITLE
platform/host logic and Cylc integration

### ISSUE THREAD

**Issue by oliver-sanders** [metomi/rose#2445]
Two bits of functionality depend on extracting hosts from Cylc workflows:

* `rose_prune` must get the host a task ran on.
* `fcm_make` must get the host a task will run on.

Broken interfaces awaiting re-implementation:

* `get_suite_jobs_auths`
* `get_task_auth`

Both these will be broken by #2446 

#### some more info on the fcm_make bit

The mirroring logic used by the `fcm_make` app relies on `SuiteEngineProc.get_task_auth` which has become broken by Cylc platforms.

https://github.com/metomi/rose/blob/4f6aaa5d2ffe6d327f3034a5ceef227b005cb4af/metomi/rose/suite_engine_procs/cylc.py#L207-L228

Note the `fcm_make` logic has a "back compat" notice in it:

https://github.com/metomi/rose/blob/4f6aaa5d2ffe6d327f3034a5ceef227b005cb4af/metomi/rose/apps/fcm_make.py#L197-L198

Investigate this logic, try and find a solution which allows us to remove `SuiteEngineProc.get_task_auth`.

**Comment by dpmatthews** [comment]
The functionality is (mostly) described in the documentation: https://metomi.github.io/rose/doc/html/api/built-in/fcm_make.html
In particular look at the description of `mirror-step`.

The functionality is tested here: https://github.com/metomi/rose/tree/master/t/rose-task-run/08-app-fcm-make
`fcm_make_t5 => fcm_make2_t5`

Note that the `fcm_make.cfg` file sets `mirror.target=$ROSE_TASK_MIRROR_TARGET`.
https://github.com/metomi/rose/blob/master/t/rose-task-run/08-app-fcm-make/app/fcm_make_t5/file/fcm-make.cfg#L4
This is a deprecated setting which I don't think is required.
(We should remove this deprecated feature if possible)

We need to determine the remote host used by the `fcm_make2*` task in order to set the mirror target. In Cylc 8 I think that means:
1. Check to see if a remote host is set and use it if it is (note that this may be a command but I assume Rose already handles this).
2. Otherwise, check for a platform setting (again, this may be a command). Then lookup the hosts for that platform and choose one. I think selecting one at random should be good enough given that this feature is no longer widely used. For extra points we could check the host is accessible via ssh (which is what would happen with remote hosts specified via `rose host-select` at Cylc 7).

**Comment by oliver-sanders** [comment]
This functionality interfaces between Cylc and Rose so it is best located in Cylc-Rose (where the Cylc/Rose compatibility ranges are set).

The Cylc-Rose interface could look something like this:

```python
# cylc-rose
from cylc.flow.platforms import ...

def get_platform_from_task_def(flow, task) -> dict: ...

def get_platform_from_task_job(flow, cycle, task) -> dict: ...
```

Rose must be able to function if cylc-rose isn't install (minus this functionality of course):

```python
# metomi-rose - suite-engine-proc/cylc.py
try:
    from cylc.rose import get_platform_from_task_def, get_platform_from_task_job
    HAS_CYLC_ROSE = True
except ImportError:
    HAS_CYLC_ROSE = False
```

**Comment by wxtim** [comment]
@oliver-sanders 
> app relies on SuiteEngineProc.get_task_env

do you mean get_task_auth?

**Comment by oliver-sanders** [comment]
Yes, whoops, the two interfaces awaiting re-implementation are:

* `get_suite_jobs_auths`
* `get_task_auth`

**Comment by wxtim** [comment]
> Yes, whoops, the two interfaces awaiting re-implementation are:
> 
>     * `get_suite_jobs_auths`
> 
>     * `get_task_auth`

What about `get_tasks_auths`?

**Comment by wxtim** [comment]
I think that I've done this.
