### ISSUE TITLE
ensure rose suite-run plays nicely with Cylc 8

### ISSUE THREAD

**Issue by oliver-sanders** [metomi/rose#2474]

**Comment by wxtim** [comment]
Copied from https://github.com/cylc/cylc-flow/issues/4451

## Findings
- Workflows with no `rose-suite.conf` are totally safe. Rose will refuse to work with them.
- Workflows with a `flow.cylc` are somewhat risky because they do add files and directories , although `rose suite-run -i` subsequently fails due to the absence of the `suite.rc` file. I imagine that there is a low but non-negligable risk of users losing things by this route. 
- If users are not using `--no-run-name` cleaning out the mistakenly installed stuff should be straightforward.
- If users install a suite using `rose suite-install -i`, over the top of a `--no-run-name` workflow, or by wilful setting the name of the suite to `suite_name/runN` (perverse), the folder will look thus:

![image](https://user-images.githubusercontent.com/26465611/136415183-0f54c0e7-6aee-4190-857f-a2a3b2455be9.png)

Which looks
a) mostly harmless
b) easy enough to mop up

## Possible actions
- Add some extra checks to Rose 2019 (only works with future releases, doesn't protect users _that_ much)
- Provide a cleanup utility (potentially tricky if Rose installs non-standard stuff)

**Comment by wxtim** [comment]
Closed by changes to Rose
