### ISSUE TITLE
`pygraphviz` dependency

### ISSUE THREAD

**Issue by MetRonnie** [metomi/rose#2523]
Currently there is a dependency on `pygraphviz` which is not listed in `setup.py`.
https://github.com/metomi/rose/blob/19e6c87bf6045950d42e684219ec22ee6656e880/metomi/rosie/graph.py#L22

Digging around I found this discussion: https://github.com/metomi/rose/pull/2366#discussion_r303263303

**Comment by wxtim** [comment]
I'll make it a dep. For now.

**Comment by wxtim** [comment]
Dumping the converation

 @kinow kinow on 14 Jul 2019

This is raising an issue in my virtual environment, due to pygraphviz not being installed after pip install .. I don't see any graphviz related dependencies in setup.py... is this file used by rose or rosie? If so, we may need to include the dependencies in setup.py.
Member Author
@wxtim wxtim on 15 Jul 2019 •

Yes. Thanks!

This is nasty: disappointed - I'm afraid there is more work to be done on removing pygraphviz from the dependency tree in both rose and rosie. I failed to notice this because of the skips in the tests.

Pygraphviz can be installed via conda, but there is no surety of installing it correctly using pip, and therefore, since we are planning to remove it anyway it should be removed. It looks fairly involved, however, since it needs to change rosie graph and rose graph significantly so with the permission of @kinow @oliver-sanders I'm going to suggest that it should be a separate issue.
Member
@oliver-sanders oliver-sanders on 15 Jul 2019

Yep, this dependency has been left floating about, it will be removed in due course, I think we will copy the solution from the new Cylc Graph.
Member
@oliver-sanders oliver-sanders on 15 Jul 2019

For now either delete rosie graph or add pygraphviz to the dependencies (note it's a bit of a pain to install).
Member Author
@wxtim wxtim on 15 Jul 2019 •

@kinow I'm afraid I'm just going to leave this for this PR and create a new issue to deal with removing this. There's no point getting this test working as the item tested will be removed and re-written in the new GUI. I do not want to include pygraphviz in the package dependencies since the need for it will be removed.

issue #2369 created

**Comment by wxtim** [comment]
Having tried to add the dependency I've realized that trying to add Pygraphviz is horrible because it's reliant on a whole stack of Graphviz + C++ compiler... I think it's safer to remove/disable rosie/rose graph.

**Comment by oliver-sanders** [comment]
To install pygraphviz you typically require a second package, for Ubuntu you need `graphviz graphviz-dev`. For details see the pygraphviz installing page.

#2525 makes pygraphviz an optional dependency (which is how it was in 2019.01.x and is presently in cylc-flow).
