### ISSUE TITLE
rose documentation: google search

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#301]
We should make our documentation more visible to search engines, and embed a Google search plugin in the documentation web pages (like <a href="http://www.youtube.com/watch?v=uUB04YCUQ7k">this</a>).

**Comment by benfitzpatrick** [comment]
Definitely useful...

**Comment by kaday** [comment]
I want a like button so I can like this!

**Comment by arjclark** [comment]
This has come up again via one of our user groups (ultimately due to the lack of single-page documentation which would reduce the need to do this as you could just text search within the browser page).

The following code snippet will let you google search the latest incarnation of the documentation:

```
    <form method="get" action="http://www.google.com/search">
      <a href=".">Rose Documentation</a>
      <input type="text"   name="q" size="20"
      maxlength="255" value="" />
      <input type="submit" value="Google Search" />
      <input type="hidden"  name="sitesearch"
      value="http://metomi.github.io/rose/"/>
    </form>
```

I guess, based on discussions with Ben, that the main issue we have is that this will only search the latest version of the documentation and not the documentation it is in?

**Comment by oliver-sanders** [comment]
- #1891 Added a single page view which should largely mitigate the need for a search box.
- For site searching we now have the option of javascript solutions (e.g. https://github.com/Tipue/Tipue-Search)

**Comment by arjclark** [comment]
> #1891 Added a single page view which should largely mitigate the need for a search box.

This pretty much eliminated any urgency for doing this any time soon, so will bump the milestone back.
